### ISSUE TITLE
Local LLM (Ollama/llama.cpp + whisper/piper)

### ISSUE THREAD

**Issue by sammcj** [pipecat-ai/pipecat#139]
It would be great if you could provide examples using this with local LLM tooling (e.g. Ollama / llama.cpp, whisper/piper etc...)

Neat project!

**Comment by aconchillo** [comment]
Hi @sammcj ! We have a couple of examples. One that uses Moondream (for vision) and the other that uses Whisper.

Whisper (all local): https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/13a-whisper-local.py
Moondream: https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/12-describe-video.py

We might have to update the Whisper one I believe. I saw some issues last time I ran it.

**Comment by sammcj** [comment]
Oh I don’t know how I missed that they were local options!

That’s great to see, I’ll be trying them out for sure.

thanks again!

**Comment by aconchillo** [comment]
No problem! We are quickly improving things and I'm sure we have missed tons of stuff, so feel free to report anything you see. Thank you!!! :pray:
