### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by akashloop** [pipecat-ai/pipecat#142]
______________________________________ ERROR collecting src/pipecat/pipeline/merge_pipeline.py ______________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/pipeline/merge_pipeline.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/pipeline/merge_pipeline.py:2: in <module>
    from pipecat.pipeline.frames import EndFrame, EndPipeFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
_____________________________ ERROR collecting src/pipecat/processors/aggregators/openai_llm_context.py _____________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/processors/aggregators/openai_llm_context.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/processors/aggregators/openai_llm_context.py:13: in <module>
    from openai._types import NOT_GIVEN, NotGiven
E   ModuleNotFoundError: No module named 'openai'
_______________________________ ERROR collecting src/pipecat/serializers/abstract_frame_serializer.py _______________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/serializers/abstract_frame_serializer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/serializers/abstract_frame_serializer.py:3: in <module>
    from pipecat.pipeline.frames import Frame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
__________________________________ ERROR collecting src/pipecat/serializers/protobuf_serializer.py __________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/serializers/protobuf_serializer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/serializers/protobuf_serializer.py:3: in <module>
    from pipecat.pipeline.frames import AudioFrame, Frame, TextFrame, TranscriptionFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
__________________________________________ ERROR collecting src/pipecat/services/azure.py ___________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/services/azure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/services/azure.py:14: in <module>
    from openai import AsyncAzureOpenAI
E   ModuleNotFoundError: No module named 'openai'
________________________________________ ERROR collecting src/pipecat/services/fireworks.py _________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/services/fireworks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/services/fireworks.py:7: in <module>
    from pipecat.services.openai import BaseOpenAILLMService
src/pipecat/services/openai.py:25: in <module>
    from pipecat.processors.aggregators.openai_llm_context import OpenAILLMContext, OpenAILLMContextFrame
src/pipecat/processors/aggregators/openai_llm_context.py:13: in <module>
    from openai._types import NOT_GIVEN, NotGiven
E   ModuleNotFoundError: No module named 'openai'
__________________________________________ ERROR collecting src/pipecat/services/ollama.py __________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/services/ollama.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/services/ollama.py:7: in <module>
    from pipecat.services.openai import BaseOpenAILLMService
src/pipecat/services/openai.py:25: in <module>
    from pipecat.processors.aggregators.openai_llm_context import OpenAILLMContext, OpenAILLMContextFrame
src/pipecat/processors/aggregators/openai_llm_context.py:13: in <module>
    from openai._types import NOT_GIVEN, NotGiven
E   ModuleNotFoundError: No module named 'openai'
__________________________________________ ERROR collecting src/pipecat/services/openai.py __________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/services/openai.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/services/openai.py:25: in <module>
    from pipecat.processors.aggregators.openai_llm_context import OpenAILLMContext, OpenAILLMContextFrame
src/pipecat/processors/aggregators/openai_llm_context.py:13: in <module>
    from openai._types import NOT_GIVEN, NotGiven
E   ModuleNotFoundError: No module named 'openai'
_____________________________________ ERROR collecting src/pipecat/transports/services/daily.py _____________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/transports/services/daily.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/pipecat/transports/services/daily.py:18: in <module>
    from daily import (
E   ImportError: cannot import name 'CallClient' from partially initialized module 'daily' (most likely due to a circular import) (/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/src/pipecat/transports/services/daily.py)
____________________________________ ERROR collecting tests/integration/integration_azure_llm.py ____________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/integration/integration_azure_llm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/integration_azure_llm.py:3: in <module>
    from pipecat.pipeline.openai_frames import OpenAILLMContextFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.openai_frames'
___________________________________ ERROR collecting tests/integration/integration_ollama_llm.py ____________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/integration/integration_ollama_llm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/integration_ollama_llm.py:2: in <module>
    from pipecat.pipeline.openai_frames import OpenAILLMContextFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.openai_frames'
___________________________________ ERROR collecting tests/integration/integration_openai_llm.py ____________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/integration/integration_openai_llm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/integration_openai_llm.py:3: in <module>
    from pipecat.pipeline.openai_frames import OpenAILLMContextFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.openai_frames'
____________________________________________ ERROR collecting tests/test_aggregators.py _____________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_aggregators.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_aggregators.py:6: in <module>
    from pipecat.pipeline.aggregators import (
E   ModuleNotFoundError: No module named 'pipecat.pipeline.aggregators'
____________________________________________ ERROR collecting tests/test_aggregators.py _____________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_aggregators.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_aggregators.py:6: in <module>
    from pipecat.pipeline.aggregators import (
E   ModuleNotFoundError: No module named 'pipecat.pipeline.aggregators'
____________________________________________ ERROR collecting tests/test_ai_services.py _____________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_ai_services.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_ai_services.py:6: in <module>
    from pipecat.pipeline.frames import EndFrame, Frame, TextFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
____________________________________________ ERROR collecting tests/test_ai_services.py _____________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_ai_services.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_ai_services.py:6: in <module>
    from pipecat.pipeline.frames import EndFrame, Frame, TextFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
______________________________________________ ERROR collecting tests/test_pipeline.py ______________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_pipeline.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pipeline.py:5: in <module>
    from pipecat.pipeline.aggregators import SentenceAggregator, StatelessTextTransformer
E   ModuleNotFoundError: No module named 'pipecat.pipeline.aggregators'
______________________________________________ ERROR collecting tests/test_pipeline.py ______________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_pipeline.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pipeline.py:5: in <module>
    from pipecat.pipeline.aggregators import SentenceAggregator, StatelessTextTransformer
E   ModuleNotFoundError: No module named 'pipecat.pipeline.aggregators'
________________________________________ ERROR collecting tests/test_protobuf_serializer.py _________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_protobuf_serializer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_protobuf_serializer.py:3: in <module>
    from pipecat.pipeline.frames import AudioFrame, TextFrame, TranscriptionFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
________________________________________ ERROR collecting tests/test_protobuf_serializer.py _________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_protobuf_serializer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_protobuf_serializer.py:3: in <module>
    from pipecat.pipeline.frames import AudioFrame, TextFrame, TranscriptionFrame
E   ModuleNotFoundError: No module named 'pipecat.pipeline.frames'
________________________________________ ERROR collecting tests/test_websocket_transport.py _________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_websocket_transport.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_websocket_transport.py:7: in <module>
    from pipecat.transports.websocket_transport import WebSocketFrameProcessor, WebsocketTransport
E   ModuleNotFoundError: No module named 'pipecat.transports.websocket_transport'
________________________________________ ERROR collecting tests/test_websocket_transport.py _________________________________________
ImportError while importing test module '/mnt/c/Users/DELL/Documents/pipchatbot/pipecat/tests/test_websocket_transport.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/loop/miniconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_websocket_transport.py:7: in <module>
    from pipecat.transports.websocket_transport import WebSocketFrameProcessor, WebsocketTransport
E   ModuleNotFoundError: No module named 'pipecat.transports.websocket_transport'
====================================================== short test summary info ======================================================
ERROR src/pipecat/pipeline/merge_pipeline.py
ERROR src/pipecat/processors/aggregators/openai_llm_context.py
ERROR src/pipecat/serializers/abstract_frame_serializer.py
ERROR src/pipecat/serializers/protobuf_serializer.py
ERROR src/pipecat/services/azure.py
ERROR src/pipecat/services/fireworks.py
ERROR src/pipecat/services/ollama.py
ERROR src/pipecat/services/openai.py
ERROR src/pipecat/transports/services/daily.py
ERROR tests/integration/integration_azure_llm.py
ERROR tests/integration/integration_ollama_llm.py
ERROR tests/integration/integration_openai_llm.py
ERROR tests/test_aggregators.py
ERROR tests/test_aggregators.py
ERROR tests/test_ai_services.py
ERROR tests/test_ai_services.py
ERROR tests/test_pipeline.py
ERROR tests/test_pipeline.py
ERROR tests/test_protobuf_serializer.py
ERROR tests/test_protobuf_serializer.py
ERROR tests/test_websocket_transport.py
ERROR tests/test_websocket_transport.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 22 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by akashloop** [comment]
websocket_transport is not present  in my code

**Comment by aconchillo** [comment]
Hi @akashloop ! Wow, a bunch of errors there! Could you please share what platform (OS version and Python version) are you using? Thanks!

**Comment by vipyne** [comment]
closing as this is stale.  feel free to open a new issue with OS version and Python version info if you see the error again @akashloop !

**Comment by adv-11** [comment]
![image](https://github.com/user-attachments/assets/96feff7e-9261-4613-96ab-d22c63c31dac)

Same error, any fixes?

**Comment by Pixeliate** [comment]
It is possible if packages are not installed properly. 
Try this **pip install pipecat-ai**

**Comment by adv-11** [comment]
> It is possible if packages are not installed properly. Try this **pip install pipecat-ai**

@Pixeliate i think for me the issue was platform, got a msg from a dev that their daily package is linux only. windows one will come around Q1 2025
