### ISSUE TITLE
Simpler context management for LLMs

### ISSUE THREAD

**Issue by chadbailey59** [pipecat-ai/pipecat#147]
As [mentioned in Discord](https://discord.com/channels/1239284677165056021/1239289240756551781/1240604191047549029), Pipecat bots don't automatically maintain an LLM context object for you; instead, you have to use a bunch of aggregators and other tools to manage that yourself.

We originally built that because there were plenty of use cases where you didn't necessarily want to automatically store everything the user or bot said in the context, but we should consider adding an 'easy mode' that does this for you.

**Comment by ramishi** [comment]
Will you please consider adding https://dify.ai/ supports? it will solve the context issue and overall LLOMps solution.

**Comment by TomTom101** [comment]
Langchain's message history comes in handy here, see the [langchain example](https://github.com/pipecat-ai/pipecat/blob/fe71825954440e17abf00ab5c786c38af9afd0c1/examples/foundational/07b-interruptible-langchain.py#L85). You can store the history per speaker, summarize long conversations, persist in a database etc.

**Comment by vipyne** [comment]
closing @chadbailey59 because this is stale.  feel free to open a new updated issue if needed!
