### ISSUE TITLE
ImportError: cannot import name 'CallClient' from 'daily'

### ISSUE THREAD

**Issue by yangmingming** [pipecat-ai/pipecat#151]
I already install these module
```
pip install pipecat-ai fastapi requests openai daily click
```

<img width="1436" alt="image" src="https://github.com/pipecat-ai/pipecat/assets/3910971/9c965659-ac19-4e1f-8fbe-d25d1d4ed75c">

Below is the software and system information
<img width="1439" alt="image" src="https://github.com/pipecat-ai/pipecat/assets/3910971/a734e6ba-776a-4e49-9c3c-0f93dfa99da7">

Thanks~

**Comment by aconchillo** [comment]
Hi! @yangmingming ! You need to install `daily-python` instead of `daily`.

```
pip install daily-python 
```

or

```
pip install pipecat-ai[daily]
```

Hope this helps

**Comment by aconchillo** [comment]
And actually, from the `simple-chatbot` fodler you can just do:

```
pip install -r requirements.txt
```

and it will install all the needed dependencies.

**Comment by yangmingming** [comment]
My mistake, thanks for your reply. It has been installed successfully. I will register again and need to go to the API to experience the Chinese support situation. Many thanks
