### ISSUE TITLE
Question: Storytelling example: Why toggle setLocalAudio() every turn?

### ISSUE THREAD

**Issue by TomTom101** [pipecat-ai/pipecat#180]
First up, brilliant project! Still trying to wrap my head around the concept, but making some baby steps.

My question is: Why do we have to toggle recording when at the same time the "interruptible" feature is demoed in other examples?

```typescript
if (e.data?.cue === "user_turn") {
  // Delay enabling local mic input to avoid feedback from LLM
  setTimeout(() => daily.setLocalAudio(true), 500);
  setStoryState("user");
} else {
  daily.setLocalAudio(false);
  setStoryState("assistant");
}
```

Is the "always listening" feature a unique one of the Daily default video call screen which does not apply to custom apps? Would it record the audio of the TTS output (which is a typical problem of any speech-to-speech systems I have written myself)?

Thanks for clarification, looking forward to v0.0.24 :)

**Comment by aconchillo** [comment]
I think this was just an example to show how you would use cues, but Storytelling could be adjusted to use interruptions.

**Comment by TomTom101** [comment]
> but it would probably take some re-working of the prompts to tell the bot what to do when the user interrupts.
Can you hint me towards an example which shows what needs to be done in the prompt to support it?

**Comment by vipyne** [comment]
hi @TomTom101 - thank you for this issue.  I'm closing it as it is a little stale at this point, but feel free to open a new issue if this is still an open question for you.
