### ISSUE TITLE
Deepgram STT

### ISSUE THREAD

**Issue by ajram23** [pipecat-ai/pipecat#203]
Any plans to add Deepgram Speech to Text, performs better than whisper in many cases.

**Comment by janwout** [comment]
You can configure deepgram, so daily will use it: https://www.daily.co/blog/add-live-transcription-to-a-daily-call-with-our-newest-api/

**Comment by aconchillo** [comment]
If you use Daily you can already enabled it with `transcription_enabled` and then call `transport.capture_participant_transcription(...)`.

For local transport we should definitely add a `DeepgramSTTService` in `services/deepgram.py`.

**Comment by ajram23** [comment]
@aconchillo I was referring to local!

**Comment by aconchillo** [comment]
> @aconchillo I was referring to local!

I figured since I know you are working with local stuff, just added the Daily answer for completion :smiley: . Let's see if we have time this week to add it.

**Comment by aconchillo** [comment]
This is now supported with `DeepgramSTTService` in 0.0.30. Closing.
