### ISSUE TITLE
WARNING: pipecat-ai 0.0.29 does not provide the extra 'deepgram'

### ISSUE THREAD

**Issue by sardar1592** [pipecat-ai/pipecat#221]
I am trying to install pipecat with this in the requirements.txt `pipecat-ai[deepgram,openai]`

But it returns the error: 

`WARNING: pipecat-ai 0.0.29 does not provide the extra 'deepgram'`

**Comment by aconchillo** [comment]
Hi, thank you! The reason is because the current Deepgram TTS service uses HTTP connections so there's no need for any deepgram depdencies. However, PR #222 uses `deepgram-sdk` and it's added as a dependency.

**Comment by aconchillo** [comment]
This is now fixed in 0.0.30. Closing.
