### ISSUE TITLE
Twilio-chatbot exception

### ISSUE THREAD

**Issue by paulcowles** [pipecat-ai/pipecat#262]
I've tried running the example locally and within docker. 

It always fails in the same way for me:

`
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "...uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...

 File ".../pipecat/examples/twilio-chatbot/bot.py", line 39, in run_bot
    serializer=TwilioFrameSerializer(stream_sid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TwilioFrameSerializer.__init__() takes 1 positional argument but 2 were given
`

**Comment by aconchillo** [comment]
Thank you for reporting this. An issue was fixed here https://github.com/pipecat-ai/pipecat/commit/dd402da9e56fe409995d1a114da7d560c09aa017.

To use the latest example you need to use the repo version. You cna follow these instructions: https://github.com/pipecat-ai/pipecat?tab=readme-ov-file#hacking-on-the-framework-itself

**Comment by paulcowles** [comment]
Thanks, that got me up and running with the example.

**Comment by aconchillo** [comment]
This is now fixed with Pipecat 0.0.35
