### ISSUE TITLE
[Feature Request] Real-Time Usage Count for Each Service Provider

### ISSUE THREAD

**Issue by gaceladri** [pipecat-ai/pipecat#264]
**Description:**
To enhance the development of consumer-facing applications, it would be extremely beneficial to have an out-of-the-box feature that provides a real-time counter for the usage of tokens/characters for various services such as LLMs (Language Models), TTS (Text-to-Speech), STT (Speech-to-Text), and others. This feature would enable developers to set and monitor usage limits effectively.

**Benefits:**
- Allows developers to manage and control the usage of different service providers.
- Facilitates the setting of usage limits for better resource allocation and cost management.
- Provides real-time insights into the consumption patterns of various services.

**Use Case:**
As a developer building a consumer-facing application, I want to set a usage limit on the number of tokens/characters for services like LLMs, TTS, and STT. Having a real-time counter integrated into the system would allow me to track usage efficiently and ensure that my application stays within the predefined limits.

**Suggested Implementation:**
- Introduce a real-time counter for each service provider.
- Display the current usage count of tokens/characters.
- Provide an option to set usage limits and receive notifications/alerts when limits are approaching or exceeded.

**Conclusion:**
Implementing a real-time usage counter for service providers would greatly improve the ability of developers to manage and optimize the use of various services, leading to more efficient and cost-effective applications.

**Comment by vipyne** [comment]
closing with #343
