### ISSUE TITLE
[BUG] Silero expects different number of samples

### ISSUE THREAD

**Issue by maxwelllwang** [pipecat-ai/pipecat#272]
This error just started appearing this afternoon, on the latest version of the code, didn't update any libraries, same daily room. Don't know what could have caused this

```

2024-06-30 05:51:24.814 | ERROR    | pipecat.vad.silero:voice_confidence:74 - Error analyzing audio with Silero VAD: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/vad/model/vad_annotator.py", line 26, in forward
    if _2:
      _3 = torch.format(_0, (torch.size(x0))[-1])
      ops.prim.RaiseException(_3, "builtins.ValueError")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
      pass

Traceback of TorchScript, original code (most recent call last):
  File "/home/keras/notebook/nvme1/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 484, in forward
        num_samples = 512 if sr == 16000 else 256
        if x.shape[-1] != num_samples:
            raise ValueError(f"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    
        batch_size = x.shape[0]
builtins.ValueError: Provided number of samples is 640 (Supported values: 256 for 8000 sample rate, 512 for 16000)

```

**Comment by aconchillo** [comment]
Hi! Thank you for reporting this. This was fixed in Pipecat 0.0.35. https://github.com/pipecat-ai/pipecat/releases/tag/v0.0.35

**Comment by aconchillo** [comment]
There's also a pending PR to be able to switch Silero VAD versions #271 . However, it will only work starting with v5.0.

**Comment by maxwelllwang** [comment]
yup that did it! 

Really appreciate the support, this library is brilliant, can't wait to show you guys what I've been able to build with it

**Comment by aconchillo** [comment]
> yup that did it!
> 
> Really appreciate the support, this library is brilliant, can't wait to show you guys what I've been able to build with it

Can't wait either!

**Comment by XavierSeh** [comment]
Hey @aconchillo i am also facing the above issue, what exactly do i have to update?

**Comment by aconchillo** [comment]
> Hey @aconchillo i am also facing the above issue, what exactly do i have to update? Do i have to make changes in code for this? but i am actually not using pipecat i am directly using silero-vad like this: torch.hub.load( repo_or_dir="snakers4/silero-vad", model="silero_vad", force_reload=False, onnx=False, )
> 
> do you have any idea why this could be happening?

If you don't use Pipecat then you can do one of these things:

- Specify v4.0, that is `repo_or_dir="snakers4/silero-vad:v4.0"`.
- The number of audio frames you pass to Silero needs to be 512 if your sample rate is 16000 or 256 of your sample rate is 8000. That's how I solved it in Pipecat.

I hope this helps.
