### ISSUE TITLE
Multiple function calls openai

### ISSUE THREAD

**Issue by cristobal-larach** [pipecat-ai/pipecat#292]
in the file services.openai.py, why is line 147 `function_name += tool_call.function.name` and not `function_name = tool_call.function.name`?

In particular, i am getting the following error:
Uncaught exception in LLMUserContextAggregator#0: The LLM tried to call a function named 'collect_namecollect_agecollect_payment_method', but there isn't a callback registered for that function.

it happens whenever i execute a function, for example, giving my full name, then the flow goes on to collecting my age, and i try to correct my full name saying "oh, i am sorry, my name is not {previous}. it is {new_name}". I have noticed that in the patient-intake example, every function call modifies the context and just allows one function tool. Can i keep a context with many function tools (so as to call them more than once during the flow of events).??

**Comment by cristobal-larach** [comment]
Also, is there any way to add tools that are different to functions (for example, file_search to enable and enhance Retrieval Augmented Generation)? Thanks!

**Comment by cartesis07** [comment]
same issue I had to change the class

**Comment by aconchillo** [comment]
I believe this PR https://github.com/pipecat-ai/pipecat/pull/346 will fix this issue.

**Comment by agilebean** [comment]
> same issue I had to change the class

@cartesis07 how did you change the class? care to share the code?

**Comment by aconchillo** [comment]
Closing. Pretty sure this was fixed in Pipecat 0.0.42. Feel free to reopen or open a new issue if it's not working. :pray:
