### ISSUE TITLE
how to create the images for robot base on one image?

### ISSUE THREAD

**Issue by cqnimin** [pipecat-ai/pipecat#294]
hi guys, is there a tool to create the images for the chatbot base on one image? could you help recommend， thanks..

**Comment by wtlow003** [comment]
> hi guys, is there a tool to create the images for the chatbot base on one image? could you help recommend， thanks..

Are you referring to something like sprite animation or animated avatar?

**Comment by aconchillo** [comment]
I believe the chatbot images were generated by Midjourney. Right now, we don't have any support for generating avatars, mostly because Pipecat is a realtime framework. Right now you can create the avatars separately and just load them as images.

**Comment by cqnimin** [comment]
got it. help a lot. thanks guys....

**Comment by vipyne** [comment]
this seems resolved. closing the issue.
