### ISSUE TITLE
openai.BadRequestError: Error code: 400 - {'error': {'message': "An assistant message with 'tool_calls' must be followed by tool messages responding to each '

### ISSUE THREAD

**Issue by geekofycoder** [pipecat-ai/pipecat#309]
This is the issue that I am getting after binding the tool with llm.The bot pauses and if we speak anything else it throws the error.Can someone guide me through this

**Comment by TomTom101** [comment]
Do you have a full example?

**Comment by geekofycoder** [comment]
Yes it is the same...

**Comment by TomTom101** [comment]
Then maybe closer this one as it apparently is a duplicate?
