### ISSUE TITLE
Can other transports be used

### ISSUE THREAD

**Issue by pxz2016** [pipecat-ai/pipecat#325]
Such as livekit: End to end stack for WebRTC

**Comment by aconchillo** [comment]
Yes, absolutely, as soon as someone adds the LiveKit transport. But currently, that's not implemented.

**Comment by ashutoshsaboo** [comment]
Big +1 on this request! Would be super interested in livekit support for pipecat!

**Comment by TomTom101** [comment]
Gotta say their API sounds familiar:
```python
async def entrypoint(ctx: JobContext):
2  vad = silero.VAD()
3  stt = deepgram.STT()
4  llm = openai.LLM()
5  tts = elevenlabs.TTS()
6  assistant = VoiceAssistant(vad, stt, llm, tts, allow_interruptions=True)
7  assistant.set_system_message(["You are a voice assistant created by LiveKit."])
8  await assistant.say('Hello, how can I help you today?')
9
10  @ctx.room.on("participant_connected")
11  def _on_participant_connected(participant:
12                               rtc.RemoteParticipant):
13    assistant.start(ctx.room, participant)
14  

```

**Comment by joachimchauvet** [comment]
I'm planning to work on LiveKit whenever I have some free time.
Has anybody started working on it already?

**Comment by q815101630** [comment]
> I'm planning to work on LiveKit whenever I have some free time. Has anybody started working on it already?

Hi @joachimchauvet Do you have progress, would love to do the same!

**Comment by davidzhao** [comment]
I'd love to see this happen as well! @kwindla and I were talking about collaborating on this and would love to help however I can.

**Comment by nulyang** [comment]
#396 I tried adding a simple serializer to help bridge LiveKit Agents via WebSocket.

**Comment by joachimchauvet** [comment]
> Hi @joachimchauvet Do you have progress? would love to do the same!

Yes, but I'm not quite there yet. I've been able to connect to a LiveKit room and send TTS audio from my Pipecat pipeline, but I'm running into a few issues with some callback handlers and receiving frames from participants.
Once I've tidied things up and have something decent enough to share, I'll post an update here. Still haven't gotten around to video yet, though.

**Comment by ashutoshsaboo** [comment]
@davidzhao any plans on shipping livekit support for pipecat? One of the reasons not able to use pipecat & livekit, is primarily because of lack of livekit support and vice-versa.

**Comment by giantamoeba** [comment]
I would like to add my voice to the others, livekit-transport would be fantastic especially video, that would be the last missing puzzle piece for a fully local solution. I hope I am not missing anything but I think the local transport does not support video or image input.

**Comment by pushpak1300** [comment]
Livekit  will be good option.

**Comment by ChrisFeldmeier** [comment]
+1 for live kit here, if it is really needed I can help to build livekit pipecat module.

**Comment by ChrisFeldmeier** [comment]
@joachimchauvet : Can you send me a test main.py or so with what you dev livekit it, or a example how to use it. (I know it is still in dev, but I could optimized it with your code and help you)

**Comment by joachimchauvet** [comment]
> @joachimchauvet : Can you send me a test main.py or so with what you dev livekit it, or a example how to use it. (I know it is still in dev, but I could optimized it with your code and help you)

Sure! I'm on my phone right now but I'll send that over in the morning (CET) with the latest changes I have locally.

**Comment by joachimchauvet** [comment]
I added an example here: https://github.com/joachimchauvet/pipecat-livekit/blob/main/examples/foundational/01b-livekit-audio.py
It requires livekit-api to generate the token.

**Comment by kwindla** [comment]
We're happy to merge this into pipecat main any time.

**Comment by linyubupa** [comment]
> I added an example here: https://github.com/joachimchauvet/pipecat-livekit/blob/main/examples/foundational/01b-livekit-audio.py It requires livekit-api to generate the token.

@joachimchauvet s there any method to enable LiveKit transport to transmit images simultaneously, similar to how Daily transport works, by actively retrieving photos from the other participant's camera?

**Comment by joachimchauvet** [comment]
> @joachimchauvet Is there any method to enable LiveKit transport to transmit images simultaneously, similar to how Daily transport works, by actively retrieving photos from the other participant's camera?

Right now it only supports audio. It's definitely possible to implement video/images with LiveKit but that's not implemented in my LiveKit transport yet.

**Comment by aconchillo** [comment]
I think this can now be closed since we support websockets, fastapi websockets, livekit and daily.
