### ISSUE TITLE
TwilioService and OpenAI TTS service incompatible 

### ISSUE THREAD

**Issue by bhaktatejas922** [pipecat-ai/pipecat#347]
voice is super low and slow? Im using the FastAPI websocket instead of Daily doing
           params=FastAPIWebsocketParams( audio_out_enabled=True, audio_out_sample_rate=24_000,

I think there's some assumption made in the fastapi websocket of elevenlabs tts since that works fine
The TwilioFrameSerializer serialize and deserialize assume 16000 instead of 24000. Having it take in frequency as an input/output respectively should fix it

**Comment by aconchillo** [comment]
Good catch! Thank you! Should be fixed in the PR mentioned above.
