### ISSUE TITLE
Question : can we record audio while using daily transport for both input and output 

### ISSUE THREAD

**Issue by prem-observe** [pipecat-ai/pipecat#351]
I want to capture the audio we are receiving from daily input and the audio we are sending to the output transport. any straightforward way to do that?

**Comment by aconchillo** [comment]
If you use the `DailyTransport` then it should be super easy. The transport has a `start_recording()` method with the same arguments as https://reference-python.daily.co/api_reference.html#daily.CallClient.start_recording.

This will use Daily's recording functionality. Of course, your room must be configured with recordings enabled.

https://docs.daily.co/guides/products/live-streaming-recording

**Comment by aconchillo** [comment]
Closing. Feel free to reopen if you find any issues.

**Comment by prem-observe** [comment]
Hey @aconchillo , Thanks i will check this out, however my question was more general. for ex. In case of Webhook transport/server. what would be the recommended way to record the audio.

i was able to come up with adding a recorder service in the pipeline after the input and before the output which saves audio frames to a file and then redirects them back to the queue. however this had some challenges, tts output is not continuous and it is hard to get the timing of the segment right on the complete audio of the call.
