### ISSUE TITLE
If the user turns off the camera, the UserImageRequestFrame becomes useless

### ISSUE THREAD

**Issue by linyubupa** [pipecat-ai/pipecat#353]
If the user turns off the camera, the UserImageRequestFrame becomes useless, causing the entire pipeline to hang due to the absence of an ImageRawFrame. Do you have any suggestions to solve this issue

**Comment by linyubupa** [comment]
how can I know user's camera is off

**Comment by aconchillo** [comment]
That's a good one.... If you are using `DailyTransport` we need to expose `on_participant_updated`. Then you can add a handler for it and check the state of the `microphone`.  So, `participant["media"]["camera"]["state"]`

https://reference-python.daily.co/types.html#participant
https://reference-python.daily.co/types.html#participantmedia
