### ISSUE TITLE
UserIdleProcessor ignores timeout

### ISSUE THREAD

**Issue by agilebean** [pipecat-ai/pipecat#360]
## Current Code
Ran the [pipecat example of idle user check](https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/17-detect-user-idle.py).

## Expected Behavior
The pipeline should wait the specified timeout parameter in seconds

## Current Behavior
The callback (`user_idle_callback`) is called repeatedly without the timeout.

**Comment by skelleex** [comment]
Having this same error any idea why this happens?

**Comment by agilebean** [comment]
is anybody watching over bugs that occur with official pipecat demos?

**Comment by onlyrohits** [comment]
Following this.

**Comment by aconchillo** [comment]
I just tried on `main` and it works for me. It's possible that this got fixed along the way since August. I will close the issue for now. Please, feel free to reopen if it's not working for you. :pray:
