### ISSUE TITLE
 cannot import name 'CallClient

### ISSUE THREAD

**Issue by ouyangshaoxia** [pipecat-ai/pipecat#372]
"Ubuntu 18.04
CUDA Version: 11.6
I am facing issues as described below when I'm trying to use it normally according to the guide."
How shold i do

python app.py
 
Traceback (most recent call last):
  File "/mnt/D/pipecat/app.py", line 11, in <module>
    from pipecat.transports.services.daily import DailyParams, DailyTransport
  File "/home/yyq/miniconda3/envs/pipecat/lib/python3.10/site-packages/pipecat/transports/services/daily.py", line 19, in <module>
    from daily import (
ImportError: cannot import name 'CallClient' from 'daily' (/home/yyq/miniconda3/envs/pipecat/lib/python3.10/site-packages/daily.py)

**Comment by kuzma2022** [comment]
same error

**Comment by aconchillo** [comment]
Hi! How did you instal Pipecat?

**Comment by ouyangshaoxia** [comment]
"Ubuntu 18.04
CUDA Version: 11.6

just using pip install pipecat-ai

Because when I install daily-python
pip3 install daily-python

ERROR: Could not find a version that satisfies the requirement daily-python (from versions: none)
ERROR: No matching distribution found for daily-python

**Comment by aconchillo** [comment]
Oh, right. This is because `daily-python` at least needs glibc 2.35 and Ubuntu 18.04 only has 2.27. Unfortunately, as of today, I can only suggest to update to Ubuntu 22.04.
