### ISSUE TITLE
Unable to change TTS language. Using Rtvi web-demo with pipecat backend.

### ISSUE THREAD

**Issue by ttamoud** [pipecat-ai/pipecat#375]
Currently, there is no functional way to change the Text-to-Speech (TTS) language . While the system is intended to support French ("fr") in the frontend, as a language option, this setting is not being properly propagated through the application stack. This issue affects the user experience as it prevents the bot from speaking in any other language.

Detailed breakdown of the issue:

Frontend Configuration:

In config.ts, we have a language definition for French:
export const languages: Language[] = [
  {
    language: "French",
    model_id: "sonic-multilingual",
    code: "fr",
    voice: "a8a1eb38-5f15-4c1d-8722-7ac0f329727d",
  },
];
However, this language setting is not being used in the default configuration or in any language selection logic.
Voice Selection:

The VoiceSelect component in the frontend only allows selection of voices, not languages.
There is no separate language selection component.
Configuration Update:

When updating the TTS configuration (e.g., when changing voices), the language is not included:
updateConfig({
  tts: { voice: voice.id },
});
Backend Configuration Handling:

In rtvi.py, the RTVITTSConfig class does not include a language field.
The _handle_setup method in the RTVIProcessor does not extract or use a language setting from the configuration.
TTS Service Initialization:

When initializing the CartesiaTTSService in rtvi.py, no language parameter is passed:
self._tts = self._tts_cls(
    name="TTS",
    api_key=self._tts_api_key,
    voice_id=voice,
    model_id="sonic-multilingual"
)
Cartesia API Call:

In cartesia.py, the run_tts method does not include a language parameter in the API call to Cartesia.
Steps to reproduce:

Start the application.
Attempt to change the language to French.
Interact with the bot.
Expected behavior:
The bot should speak in French when the French language is selected.

Actual behavior:
The bot continues to speak in the default language, regardless of any attempt to change the language.

**Comment by markbackman** [comment]
We've made a number of changes related to language selection. I can confirm that this works both for TTS services and when controlling them via RTVI (tested with RTVI 0.2.x).

@ttamoud is this issue resolved for you?

**Comment by ttamoud** [comment]
Yes Mark thanks for replying.
I've been closely following rtvi and pipecat updates i noticed few days ago that it was fixed. It's all good now.
Thanks for all the great work your teams are doing 💪🏼

**Comment by markbackman** [comment]
Thanks for confirming and the kind words! 🙌
