### ISSUE TITLE
question: Is there a way to interrupt speech only if the user has spoken more than N number of words

### ISSUE THREAD

**Issue by nisalr** [pipecat-ai/pipecat#386]
I was wondering whether we can prevent interruptions when the user doesn't say much. For example, if the user just says "Hmm", or "yes", this shouldn't trigger an interruption. To do this, we would need to look at the transcription frames and trigger a `StartInterruptionFrame` only if there is more than a certain number of words spoken. I was wondering whether there is an easy way to do this.

**Comment by SameerFulzele** [comment]
@nisalr  Did you find a solution for this?

**Comment by sebhs** [comment]
Also curious if either of you found a solution @SameerFulzele @nisalr
