### ISSUE TITLE
No low-end on AI voice with Daily.co transport

### ISSUE THREAD

**Issue by chrisnolet** [pipecat-ai/pipecat#388]
I'm integrating the Daily.co transport at the moment.

I've noticed that the low-end of the AI voice is significantly attenuated vs. LiveKit or Retell. (Normally, voices coming from ElevenLabs have quite a nice, resonant low-end.) When I connect to my ElevenLabs agent via Daily.co, the bottom end is very thin.

Interestingly, I don't get the same issue if I use Pipecat with WebSockets.

Is there a way to maintain the audio quality and low-end as the signal makes its way through Daily.co?

**Comment by golbin** [comment]
I have same issues.

**Comment by aconchillo** [comment]
Hi! Have you tried with different sample rates? By default Pipecat uses 16000. You can try `pcm_44100` as ElevenLabs output format and then set `DailyTransport.audio_out_sample_rate=44100` to match.

**Comment by aconchillo** [comment]
Actually, if you don't have the same issue with WebSocket it's probably the WebRTC encoding audio bitrate. I don't think that's exposed right now, but I can make it available. You should then try higher values. The default depends on the browser, but for example, for music a value of 192,000 works very well, the default is for sure lower.

**Comment by chrisnolet** [comment]
Thanks! I think it might be the WebRTC bitrate. (I've tried with different ElevenLabs sample rates and they're all more-or-less the same.)

Would the WebRTC bitrate need to be set on the Pipecat end, or the consumer's end, or both?

**Comment by aconchillo** [comment]
> Thanks! I think it might be the WebRTC bitrate. (I've tried with different ElevenLabs sample rates and they're all more-or-less the same.)
> 
> Would the WebRTC bitrate need to be set on the Pipecat end, or the consumer's end, or both?

Pipecat end because Pipecat is the one sending the bot's audio. I'll try to increase it by default but also make it available for people to set their own.

**Comment by aconchillo** [comment]
@chrisnolet I just checked http://relaunch.io/... Nice! Is this built with Pipecat?

**Comment by chrisnolet** [comment]
Thanks for the fix! The demo that's live today isn't with Pipecat unfortunately, although I am looking at transitioning over!
