### ISSUE TITLE
question: Is it possible to add Frames to the middle of the queue?

### ISSUE THREAD

**Issue by nisalr** [pipecat-ai/pipecat#389]
This would be useful if you want to inject TextFrames into the queue (e.g., please hold on), when a time consuming function is being executed. However, if we just add it to the task queue using task.queue_frame, the text will be spoken only after the LLM function is executed.

**Comment by aconchillo** [comment]
I believe you could just build your own frame processor which would have that time consuming function. This new frame processor could be somewhere in the pipeline and it would inject frames from that position.

**Comment by nisalr** [comment]
Thanks @aconchillo I tried this and it worked
