### ISSUE TITLE
Is it possible that if the user is deviating from the purpose of the call the bot can end the call or leave the call?

### ISSUE THREAD

**Issue by geekofycoder** [pipecat-ai/pipecat#392]
refering to the patient_intake bot can we do the proposed thing above?

**Comment by richtermb** [comment]
One way to do this might be to have an external LLM that periodically evaluates the call transcript and gauge whether the user has deviated enough from the intended purpose of the call.

**Comment by geekofycoder** [comment]
Yes I have figured it out by pushing an end frame in a function call of gpt while you await and give the command to figure it out if it should pass the endframe or not
