### ISSUE TITLE
Azure TTS streaming support

### ISSUE THREAD

**Issue by petergerten** [pipecat-ai/pipecat#407]
Hi,

it seems that all supported TTS services utilize chunked streaming output except for Azure TTS.
Any particular reason for that?

**Comment by markbackman** [comment]
The only reason was time. We've finally got around to doing this. This PR is in review: https://github.com/pipecat-ai/pipecat/pull/702.

**Comment by markbackman** [comment]
#702 is merged. This will be in the next release.
