### ISSUE TITLE
cannot run simple-chatbot

### ISSUE THREAD

**Issue by themass** [pipecat-ai/pipecat#415]
File "/Users/liguoqing/.pyenv/versions/3.11.7/lib/python3.11/site-packages/pipecat/transports/services/helpers/daily_rest.py", line 86, in create_room
    raise Exception(f"Unable to create room (status: {r.status}): {text}")
Exception: Unable to create room (status: 400): {"error":"authorization-header-error","info":"invalid authorization header"}
I am ready setting the  .env

**Comment by aconchillo** [comment]
This feels like you are missing `DAILY_API_KEY` environment variable. Once you create a Daily account you can get the API key from the dashboard.

**Comment by Amal-David** [comment]
I'm facing the same issue, even though I have the API key in env variable. Isn't there a curl to test the keys?

**Comment by aconchillo** [comment]
Maybe this will help: https://docs.daily.co/reference/rest-api/rooms/create-room#example-requests

**Comment by Amal-David** [comment]
I just realized it's because env variables don't get picked up natively in python, you have to use dotenv or environs. You might have to modify your examples accordingly so that others don't face the same issue. I was able to get it running after using dotenv

**Comment by aconchillo** [comment]
> I just realized it's because env variables don't get picked up natively in python, you have to use dotenv or environs. You might have to modify your examples accordingly so that others don't face the same issue. I was able to get it running after using dotenv

In `simple-chatbot` the file `bot.py` should pickup `.env` file that exists on that same directory. These lines:

```
from dotenv import load_dotenv
load_dotenv(override=True)
```

**Comment by Amal-David** [comment]
bot.py has it yes but as per docs, it's suggested to run server.py and I believe that's where others might be facing the issue.

**Comment by themass** [comment]
thanks ,  it is work for me 
from dotenv import load_dotenv
load_dotenv(override=True)
