### ISSUE TITLE
I really want to konw, what asr service use?

### ISSUE THREAD

**Issue by themass** [pipecat-ai/pipecat#418]
I really want to konw, what asr service use?
how to recive daily audio?
audio to text?

**Comment by aconchillo** [comment]
If you use the `DailyTransport` speech recognition is done through Deepgram internally. You cna of course, use another speech recgonition like Gladia.

To receive Daily audio, all you need to do is create a Daily account and create a room. Then, in your browser you connect to the room and you point your Pipecat bot to that room.

**Comment by aconchillo** [comment]
Closing, since this is not really an issue. Please, feel free to add something in Discussion or join the Discord channel. https://discord.gg/pipecat for further help.
