### ISSUE TITLE
what message dailyInputTransport   input?

### ISSUE THREAD

**Issue by themass** [pipecat-ai/pipecat#423]
what message dailyInputTransport   input?
text for audio?

"If it is text, how to configure STT?"

**Comment by aconchillo** [comment]
> what message dailyInputTransport input? text for audio?
> 
> "If it is text, how to configure STT?"

Hi @themass . Apologies, not sure if I understand the question. Could you please rephrase it? Thank you! :pray:

**Comment by aconchillo** [comment]
Closing, since we don't have more info. :pray:
