### ISSUE TITLE
Parallel Function calling in Openai

### ISSUE THREAD

**Issue by maxwelllwang** [pipecat-ai/pipecat#424]
because we are streaming in chunks I see the [code that appends function names](https://github.com/pipecat-ai/pipecat/blob/e038767b6f718b92f5aeeac3d07ceff8f39672e3/src/pipecat/services/openai.py#L168) but this leads to the model failing to call functions where there are multiple function calls per completion

```
pipecat.services.openai.OpenAIUnhandledFunctionException: The LLM tried to call a function named 'get_weatherget_weather', but there isn't a callback registered for that function.
```

**Comment by kwindla** [comment]
Fixed with https://github.com/pipecat-ai/pipecat/pull/522
