### ISSUE TITLE
Unable to run simple-chatbot

### ISSUE THREAD

**Issue by dhaval0108** [pipecat-ai/pipecat#431]
I am running into errors while creating the Daily room.

```
File "/Users/dhaval.shah/virtual-envs/voice-ai-service-env/lib/python3.11/site-packages/pipecat/transports/services/helpers/daily_rest.py", line 92, in create_room
    data = await r.json()
           ^^^^^^^^^^^^^^
  File "/Users/dhaval.shah/virtual-envs/voice-ai-service-env/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 200, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://dhaval-local.daily.co/rooms'
```

I have checked my environment variables and also the headers being passed in the request, they look good to me. The room creation request also returns a 200, but it seems the response format is not in the expected format. Any work around for this? 

Thank you.

**Comment by dhaval0108** [comment]
Upon visualizing the html content in the response, this is what I get

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/e2aa0ef6-5cbd-4121-a2d0-d391157eeb8f">

**Comment by aconchillo** [comment]
@dhaval0108 Hi! Thank you for reporting this. What version of Pipecat are you using? That definitely is a weird and unexpected error. Let me do some tests.

**Comment by dhaval0108** [comment]
I am using `0.0.41` version of pipecat-ai

**Comment by aconchillo** [comment]
I just created this simple example. Do you mind trying it out? You just need to set `DAILY_API_KEY` environment variable.

```
import aiohttp
import asyncio
import argparse
import os

from pipecat.transports.services.helpers.daily_rest import DailyRESTHelper, DailyRoomParams


async def main(room: str):
    async with aiohttp.ClientSession() as session:
        helper = DailyRESTHelper(
            daily_api_key=os.getenv("DAILY_API_KEY", ""),
            aiohttp_session=session
        )

        await helper.create_room(params=DailyRoomParams(name=room))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pipecat Room Creation Example")
    parser.add_argument("-r", "--room", type=str, required=True, help="Room name")

    args, unknown = parser.parse_known_args()
    asyncio.run(main(args.room))
```

**Comment by aconchillo** [comment]
A part from the room name, are you setting any other room properties? That is `DailyRoomParams(name="...", properties=DailyRoomProperties(....))`?

**Comment by dhaval0108** [comment]
Thank you for being prompt in replying to this.

I am not setting any properties, not even the room name.
The script you shared above works fine for me, it created the room with the give room name.

I notice you don't set daily api url in this sample script though, which is getting set in the simple example server.py.

**Comment by dhaval0108** [comment]
I removed that environment variable and it's working fine now! Thanks for the help.

**Comment by aconchillo** [comment]
The example below is closer to what we are doing in `simple-chatbot` (no need to specify `-r`, it will create a random room). Is the error reproducible in your case?

```
import aiohttp
import asyncio
import argparse
import os

from pipecat.transports.services.helpers.daily_rest import DailyRESTHelper, DailyRoomParams


async def main(room: str | None):
    async with aiohttp.ClientSession() as session:
        helper = DailyRESTHelper(
            daily_api_key=os.getenv("DAILY_API_KEY", ""),
            daily_api_url=os.getenv("DAILY_API_URL", 'https://api.daily.co/v1'),
            aiohttp_session=session
        )

        await helper.create_room(params=DailyRoomParams(name=room))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pipecat Room Creation Example")
    parser.add_argument("-r", "--room", type=str, required=False, help="Room name")

    args, unknown = parser.parse_known_args()
    asyncio.run(main(args.room))
```

**Comment by aconchillo** [comment]
> I removed that environment variable and it's working fine now! Thanks for the help.

Yay! :partying_face:  Which one did you remove?

**Comment by dhaval0108** [comment]
I was setting the `DAILY_API_URL` to `https://dhaval-local.daily.co`, removing that resolved this. 
Thank you again!

**Comment by aconchillo** [comment]
> I was setting the `DAILY_API_URL` to `https://dhaval-local.daily.co`, removing that resolved this. Thank you again!

Ah, makes sense. That should be Daily's REST API endpoint.
