### ISSUE TITLE
WebRTC with FASTAPI

### ISSUE THREAD

**Issue by keenborder786** [pipecat-ai/pipecat#439]
- I was wondering if it's possible to set up a transport in FastAPI that uses WebRTC with the `aiortc` package instead of plain websockets. Specifically, I'm interested in creating a transport that relays real-time audio using WebRTC within FastAPI. I’m not entirely sure how to achieve this, but I suspect it might be possible using `aiortc`.

**Comment by pushpak1300** [comment]
Support for this would be great.

**Comment by aconchillo** [comment]
I'm not very familiar with `aiortc` but it looks like a WebRTC implementation. WebRTC doesn't use websockets for sending/receiving audio/video, it uses the UDP protocol instead which is how you can achieve low-latency.

Websockets (in the context of WebRTC) are usually used for the signalling part. That is, when two participants want to send media between each other they need to know where to send the media, what media is available, etc. WebRTC doesn't define how this data is exchanged so every one implementing WebRTC has their own way of exchanging this information.

**Comment by bigly-sales-admin-repo-ai** [comment]
Ah Okay I see. I guess then if we want to use `WebRTC` we will have to use DialyCO

**Comment by keenborder786** [comment]
Ah Okay I see. I guess then if we want to use `WebRTC` we will have to use DialyCO

**Comment by aconchillo** [comment]
> Ah Okay I see. I guess then if we want to use `WebRTC` we will have to use DialyCO

If you want low-latency and scalability built-in, yes, that's your best option.

**Comment by randxie** [comment]
I have done something similar using aiortc. If you have a websocket server implementation, you can use aiortc to create an external wrapper and convert messages in both data channel and track into a format that's compatible with your websocket message definition. The performance is worse due to extra layer
