### ISSUE TITLE
Received BotStartedSpeakingFrame before CartesiaTTSService TTFB?

### ISSUE THREAD

**Issue by wjiuzh** [pipecat-ai/pipecat#442]
Hi, 

I'm implementing an rtvi demo and I've run into a problem that confuses me.
In FrameLogger, I receive BotStartedSpeakingFrame before CartesiaTTSService TTFB, Shouldn't the bot be speaking after CartesiaTTSService has processed it?

![6281725437141_ pic](https://github.com/user-attachments/assets/77097b5d-b2bb-43fb-985a-deb61797de31)

**Comment by aconchillo** [comment]
This should be fixed by this PR https://github.com/pipecat-ai/pipecat/pull/667 and will be available in the next Pipecat release.
