### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by sadimoodi** [pipecat-ai/pipecat#443]
Hello,
Thank you very much for the winderful library.
I am reading [this ](https://docs.pipecat.ai/deployment/pattern) example from your Docs but the code is not running because you are using:
`daily_rest_helper = DailyRESTHelper(
    os.getenv("DAILY_API_KEY", ""),
    os.getenv("DAILY_API_URL", 'https://api.daily.co/v1'))`

but DailyRESTHelper constructor takes an additional argument which is aiohttp_session of type aiohttp.ClientSession
so your code isnt running using pipecat version 0.0.39 not 0.0.41

the below code uses FastAPI and receives http post requests so an aiohttp.ClientSession isnt available, how to run this code? thanks

MAX_SESSION_TIME = 5 * 60  # 5 minutes
# List of require env vars our bot requires
REQUIRED_ENV_VARS = [
    'DAILY_API_KEY',
    'OPENAI_API_KEY',
    'ELEVENLABS_API_KEY',
    'ELEVENLABS_VOICE_ID']

daily_rest_helper = DailyRESTHelper(
    os.getenv("DAILY_API_KEY", ""),
    os.getenv("DAILY_API_URL", 'https://api.daily.co/v1'))

 ----------------- API ----------------- 

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)

----------------- Main ----------------- 

@app.post("/start_bot")
async def start_bot(request: Request) -> JSONResponse:
    try:
        # Grab any data included in the post request
        data = await request.json()
    except Exception as e:
        pass

    # Create a new Daily WebRTC room for the session to take place in
    try:
        params = DailyRoomParams(
            properties=DailyRoomProperties()
        )
        room: DailyRoomObject = daily_rest_helper.create_room(params=params)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Unable to provision room {e}")

**Comment by jamsea** [comment]
Hi @sadimoodi, could you try adding [this line](https://github.com/pipecat-ai/pipecat/commit/e405d7af9fd2936fc1a42a55557a651cc0eab7ef#diff-7059ebdc5a6963574b6d0a3142dbf1fbd90190a3a8dbec3fed61994cc701553dL114) back to the demo and re-running it? Looks like there's a small bug in the demo.

**Comment by vipyne** [comment]
@sadimoodi did @jamsea's suggestion work?

**Comment by sadimoodi** [comment]
> 0.0.41



> @sadimoodi did @jamsea's suggestion work?

version 0.0.41 fixes this problem

**Comment by markbackman** [comment]
Thanks for confirming @sadimoodi. Closing this issue.
