### ISSUE TITLE
Discrepancy between PyPI package and GitHub repository contents

### ISSUE THREAD

**Issue by iamheinrich** [pipecat-ai/pipecat#483]
Hi there,

I've noticed a significant difference between the content available in the GitHub repository and what gets installed via pip from PyPI.

When installing the package using `pip install pipecat-ai`, the installed version seems to be missing several modules and files that are present in the GitHub repository. Specifically, I encountered a `ModuleNotFoundError` for `pipecat.transcriptions`, which exists in the GitHub repo but not in the pip-installed package. CartesiaHttpTTSService also doesn't exist in `pipecat.services.cartesia `

Steps to reproduce:
1. `pip install pipecat-ai`
2. Try to import from missing modules, e.g., `from pipecat.transcriptions.language import Language`

Expected behavior: All modules present in the GitHub repository should be available after pip installation.

Actual behavior: Some modules are missing, leading to import errors.

Could you please look into this discrepancy and ensure that the PyPI package includes all necessary files? Alternatively, if there's a recommended way to install the full package that I'm missing, I'd appreciate some guidance.

Thank you for your time and for maintaining this project!

**Comment by jonnyjohnson1** [comment]
Same. I just take it as they're updating the package at a high rate right now. A discord post says the next released version is going to have a lot of new capabilities, and that is what you are seeing in the updates in their github.

**Comment by vipyne** [comment]
+1 to what @jonnyjohnson1 said.  closing this for now but feel free to open a new issue if it happens again.  and remember to list what version of pipecat-ai you are using.  we are moving fast, so a lot of issues get resolved with a quick update of the package.
