### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by cbora** [pipecat-ai/pipecat#501]
When I try to run the simple_chatbot example out of the box, I get an error 

`INFO:     127.0.0.1:58183 - "GET /start HTTP/1.1" 307 Temporary Redirect
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/chrisbora/workspace/pipecat/examples/simple-chatbot/bot.py", line 21, in <module>
    from pipecat.frames.frames import (
ImportError: cannot import name 'OutputImageRawFrame' from 'pipecat.frames.frames' (/Users/chrisbora/workspace/pipecat/examples/simple-chatbot/venv/lib/python3.12/site-packages/pipecat/frames/frames.py). Did you mean: 'URLImageRawFrame'?
`

**Comment by vipyne** [comment]
hi @cbora can you provide more detail and logs?  what code or command are you running.  also what platform?  thank you!

**Comment by aconchillo** [comment]
This error probably occurred trying an example from the repo with an installed version of Pipecat instead of Pipecat from the repo. In any case this particular error should now be fixed.
