### ISSUE TITLE
documentation command error

### ISSUE THREAD

**Issue by hemants1703** [pipecat-ai/pipecat#507]
In the documentation at [Installing the module](https://docs.pipecat.ai/quickstart#installing-the-module), the command that is mentioned to activate the `env/bin/activate` on windows devices is wrong since the directory is different for windows devices (not sure about unix OSes).

![image](https://github.com/user-attachments/assets/00e9e120-525c-4f73-816b-00133b4f7496)

the corrected command with the correct directory for windows devices for python3 is `source env/Scripts/activate` for windows devices...

![image](https://github.com/user-attachments/assets/ef31bc3e-3214-4a6f-95df-82dbb29e1b78)

**Comment by vipyne** [comment]
requesting a pull request to update this documentation for windows.  any takers?  thank you for flagging @hemants1703

**Comment by markbackman** [comment]
I made a docs change for this. It'll be public soon!
https://github.com/pipecat-ai/docs/pull/16
