### ISSUE TITLE
Add AWSPollyTTS

### ISSUE THREAD

**Issue by nmaswood** [pipecat-ai/pipecat#508]
# Overview

[AWS Polly](https://aws.amazon.com/polly/) is a text to speech service. It seems like it could be a good additional to the provider libraries.

P.S. 

It has a couple of services that work especially well for our use case.  I'm not sure if anyone else is interested in it as a provider, but I would love to work on the implementation of this one.

**Comment by markbackman** [comment]
This was added in: https://github.com/pipecat-ai/pipecat/pull/514.

Unfortunately, the speech generation is blocking; they don't offer any async methods. Nonetheless, we've added support and can add async methods if/when they become available.

**Comment by nmaswood** [comment]
Thank you sir!
