### ISSUE TITLE
Sample rate control issue in `AzureTTSService`

### ISSUE THREAD

**Issue by dominikroblek** [pipecat-ai/pipecat#518]
In the `AzureTTSService`, the `sample_rate` parameter does not control the actual sample rate. To do so, you need to set the `speech_synthesis_output_format`. For example:

```
speech_config.set_speech_synthesis_output_format(
        SpeechSynthesisOutputFormat.Raw48Khz16BitMonoPcm
    )
```

However, this functionality is currently not available.

**Comment by aconchillo** [comment]
This has been fixed in https://github.com/pipecat-ai/pipecat/pull/658 and will be available in next Pipecat release.
