### ISSUE TITLE
Use raw format for `AzureTTSService` output

### ISSUE THREAD

**Issue by dominikroblek** [pipecat-ai/pipecat#519]
In the `AzureTTSService` class, there is a comment that states:
```
# Azure always sends a 44-byte header. Strip it off.
yield AudioRawFrame(
        audio=result.audio_data[44:],
        sample_rate=self._sample_rate,
        num_channels=1,
    )
```

I believe this behavior occurs because the default `speech_synthesis_output_format` is being used, which is most likely in WAV format. Instead, you should consider using one of the "raw" formats, such as `SpeechSynthesisOutputFormat.Raw16Khz16BitMonoPcm`.

**Comment by aconchillo** [comment]
Thanks! This has been fixed in https://github.com/pipecat-ai/pipecat/pull/658 and will be available in the next Pipecat release.

**Comment by dominikroblek** [comment]
This doesn't look fixed to me, since you're still stripping off the first 44 bytes (as if it were wav format) here:
https://github.com/pipecat-ai/pipecat/blob/bd50201ce4df191db6d7aaa85b6568c5f618bd74/src/pipecat/services/azure.py#L303
