### ISSUE TITLE
How can we use Deepgram endpointing instead of Silero VAD?

### ISSUE THREAD

**Issue by nisalr** [pipecat-ai/pipecat#525]
Sometimes Silero detects that the user is speaking when Deepgram doesn't (and vice versa). Is there a way to just use Deepgram endpointing so that these inconsistencies don't occur?

**Comment by manish-baghel** [comment]
looks like we need to push `UserStartedSpeaking` and `UserStoppedSpeakingFrame` from `stt` layer and disable the `vad` in transport layer

**Comment by manish-baghel** [comment]
> looks like we need to push UserStartedSpeaking and UserStoppedSpeakingFrame from stt layer and disable the vad in transport layer
Or a custom frame processor which monitors STT frames and User Started/StoppedSpeaking frames
