### ISSUE TITLE
Add Openai realtime api service

### ISSUE THREAD

**Issue by janwout** [pipecat-ai/pipecat#533]
Today Openai released the realtime api, for speech to speech, adding it to pipecat could be an good addition

**Comment by mercuryyy** [comment]
Great Idea. i'm sure this will be added soon

**Comment by petergerten** [comment]
yes, that would be great!

**Comment by mr-haseeb** [comment]
yeah it will make it awesome

**Comment by manish-baghel** [comment]
There's a draft PR for the same:
https://github.com/pipecat-ai/pipecat/pull/541

**Comment by Yi-Lyu** [comment]
Looking forward to adding it soon!

**Comment by kwindla** [comment]
Added in 0.0.44!

https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/19-openai-realtime-beta.py

**Comment by kwindla** [comment]
Done
