### ISSUE TITLE
Usage of OpenAITTSService cause the user audio_out_sample_rate =24000 hz which sounds cartoonic

### ISSUE THREAD

**Issue by geekofycoder** [pipecat-ai/pipecat#612]
we have to do the
 `wf.setframerate(16000)` 
in order to retrieve the real audio of user but we have to sacrifice the recording of the bot.Since my use case was more concerned about the user side so implemented it

**Comment by geekofycoder** [comment]
Since I have selected the TTS as OpenAITTSService so we have to set the `set_audio_sample_rate=24000` for getting the bot voice correctly and in right pace(P.S:-OpenAI voices are created with out_sample_rate=24000).
But while fetching user_recordings since the normal `out_sample_rate=16000` the user voice quality is affected
so the following function for extracting only user_voice:
```
    with BytesIO() as buffer:
        with wave.open(buffer, "wb") as wf:
            wf.setnchannels(1)  
            wf.setsampwidth(2)  
            wf.setframerate(16000) #set implicitly for user_voice
            user_speech = bytearray()
            for i in range(0, len(audiobuffer._user_audio_buffer), 2):
                user_speech.extend(audiobuffer._user_audio_buffer[i:i+2])
            # wf.writeframes(audiobuffer._user_audio_buffer)
            wf.writeframes(user_speech)
        return buffer.getvalue()
```
Hope everyone finds it useful @aconchillo @adriancowham

**Comment by aconchillo** [comment]
Thank you @geekofycoder! We have changed the default output sample rate of Pipecat to be 24000. This is now in `main` and should be released this week. So, closing.
