### ISSUE TITLE
Deprecated import broken in 0.0.46

### ISSUE THREAD

**Issue by rphillips-indeed** [pipecat-ai/pipecat#636]
This deprecated import is now broken after the move of the silero classes: https://github.com/pipecat-ai/pipecat/blob/main/src/pipecat/vad/silero.py#L11 (the updated import works, but rather than giving a warning this just breaks builds)

**Comment by markbackman** [comment]
Indeed. We just patched this: https://github.com/pipecat-ai/pipecat/pull/638. Thanks for reporting.

**Comment by markbackman** [comment]
We'll cut a new pipecat release too. Apologies for this.
