### ISSUE TITLE
When a second text frame is pushed before the first one is sent to the TTS, the speech gets mixed up

### ISSUE THREAD

**Issue by nisalr** [pipecat-ai/pipecat#659]
After the recent update (0.0.44), I've noticed that speech get's mixed up (like two audio clips playing on top of each other) if two TextFrame are sent in quick succession. I've tested with Cartesia STT. Is anyone else facing the same issue?

**Comment by xpluscal** [comment]
jup

**Comment by rphillips-indeed** [comment]
We've noticed this, and based on the OP I tried 0.0.43 and still saw the same behavior, fwiw.

**Comment by vipyne** [comment]
can anyone confirm this is still an issue as of 0.0.47 ?

**Comment by Vortigern-source** [comment]
Yes is is still an issue.

**Comment by Vortigern-source** [comment]
Does anyone know of a stopgap fix?

**Comment by aconchillo** [comment]
Not a stop gap, but I have a draft PR that should fix this https://github.com/pipecat-ai/pipecat/pull/642. I hope to finish it this week and release a new Pipecat version with it.

**Comment by aconchillo** [comment]
Closing. This should now be fixed in 0.0.48. Please, feel free to reopen or create a new issue if it doesn't work. 🙏
