### ISSUE TITLE
Echo cancellation

### ISSUE THREAD

**Issue by phamtrung0633** [pipecat-ai/pipecat#670]
Do you think you guys will implement echo cancellation in the future ? Thank you

**Comment by vipyne** [comment]
It's something we are looking into.  Can you say more about your usecase?

**Comment by sadimoodi** [comment]
@vipyne  what about voice recognition? can we recognize a specific voice and make the agent only reply to it?

**Comment by markbackman** [comment]
Echo cancellation should be part of the client implementation. If you use the DailyTransport and the Daily Client (RTVI, daily-js, etc...), then echo cancellation is part of that client library. I'm going to close this. If you still need clarification, reach out on Discord.

**Comment by tanushmahalka** [comment]
I am using RTVI and Daily, but the bot's voice/ office background noise is constantly interrupting the bot. Any clue what could I have done wrong?

**Comment by markbackman** [comment]
@tanushmahalka What browser are you using to test?

**Comment by tanushmahalka** [comment]
@markbackman firefox

**Comment by markbackman** [comment]
@tanushmahalka that may be your problem. Firefox has poor echo cancelation, so if you're meeting with Firefox and don't have headphones on, the bot's audio will be looped back via the user's mic. This is a Firefox problem. Try using Chrome/Chromium or Safari. You shouldn't see any issues there.

**Comment by tanushmahalka** [comment]
Roger that. Thanks mark!
