### ISSUE TITLE
Configurable Trigger Word for Response Activation

### ISSUE THREAD

**Issue by madriss** [pipecat-ai/pipecat#711]
# Summary
In working with Pipecat, I’ve noticed that audio assistants reply to any input, regardless of whether I specify otherwise. This behavior can be limiting in scenarios where responses are only needed when explicitly prompted by a trigger word or phrase.

# Description
When using the Pipecat framework to create audio-enabled conversational agents, I observed that the assistant responds to any audio input by default. I attempted to configure the assistant to respond selectively, but it currently appears to lack the ability to wait for a specific "wake word" (e.g., "Hey GPT") before replying. This functionality would be helpful for controlling interactions in environments where responses are only desired upon a prompt.

# Feature Request
Would it be possible to add support for a configurable trigger word or wake word feature? For example, allowing developers to set a trigger word such as “Hey GPT,” so the assistant only processes and responds when that phrase is detected in the input.

Or maybe this feature already exists and I am not aware of it ? 

Thank you and I look forward to any suggestions from the community!

**Comment by aconchillo** [comment]
Hi @madriss ! Thank you for reporting this. We actually have a frame processor that does what you are requesting, it's called `WakeCheckFilter`. You can find an example here: https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/10-wake-phrase.py

Let me know if that works. Thanks again!

**Comment by madriss** [comment]
Very helpful thanks !
