### ISSUE TITLE
13 - Whisper example fails -  'resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by philtsip** [pipecat-ai/pipecat#75]
I'm running 13-whisper-transcription.py.

I made one modification to it, adding:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

To overcome this error:
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

Now, I see this cryptic error:

20 2024-03-19 00:23:29,580 🎬 Starting frame consumer thread
`````````TRANSCRIPTION`````````
20 2024-03-19 00:23:29,581 Call_joined: {'participants': ..... [DETAILS OF THE CALL]

zsh: abort      python 13-whisper-transcription.py -u  -k 

/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown                                                                                   
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by akashloop** [comment]
I am getting error 
ERROR src/pipecat/pipeline/merge_pipeline.py
ERROR src/pipecat/processors/aggregators/openai_llm_context.py
ERROR src/pipecat/serializers/abstract_frame_serializer.py
ERROR src/pipecat/serializers/protobuf_serializer.py
ERROR src/pipecat/services/azure.py
ERROR src/pipecat/services/fireworks.py
ERROR src/pipecat/services/ollama.py
ERROR src/pipecat/services/openai.py
ERROR src/pipecat/transports/services/daily.py
ERROR tests/integration/integration_azure_llm.py
ERROR tests/integration/integration_ollama_llm.py
ERROR tests/integration/integration_openai_llm.py
ERROR tests/test_aggregators.py
ERROR tests/test_aggregators.py
ERROR tests/test_ai_services.py
ERROR tests/test_ai_services.py
ERROR tests/test_pipeline.py
ERROR tests/test_pipeline.py
ERROR tests/test_protobuf_serializer.py
ERROR tests/test_protobuf_serializer.py
ERROR tests/test_websocket_transport.py
ERROR tests/test_websocket_transport.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 22 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
give me any suggestion

**Comment by chadbailey59** [comment]
I believe this should be fixed as of v0.0.13. If it isn't, let us know!
