### ISSUE TITLE
pipecat audio module is not found in bot.py

### ISSUE THREAD

**Issue by TeslaGeek** [pipecat-ai/pipecat#756]
# Description
Is this reporting a bug or feature request? 
A bug report

If reporting a bug, please fill out the following:

### Environment
- pipecat-ai version: 0.0.45
- python version: 3.10
- OS: macOS 12.7.6

### Issue description
Provide a clear description of the issue.

I am using VSCode to run simple-chatbot example. I have followed the Readme, created all the credentials, ran server.py and go to the localhost however the bot does not appear and in the terminal I receive 

from pipecat.audio.vad.silero import SileroVADAnalyzer
ModuleNotFoundError: No module named 'pipecat.audio'

I have even tried to manually force pipecat-ai installation with pip as well as pip install "pipecat-ai[silero]" and I see the requirements are already satisfied but for some reasons the code is not able to find the audio package in bot.py. My fear is other packages related to pipecat in bot.py may produce ModuleNotFound error message.

### Repro steps
List the steps to reproduce the issue.

**Comment by xingweitian** [comment]
I think you need to install a newer version of pipecat, try the latest v0.0.49?

**Comment by markbackman** [comment]
See https://github.com/pipecat-ai/pipecat/issues/758
