### ISSUE TITLE
Is livekit transport fully  supported?

### ISSUE THREAD

**Issue by muddassir-lateef** [pipecat-ai/pipecat#861]
# Description
I saw in a previous issue that livekit support was added but i dont see it being mentioned in the documentation. Is the documentation just outdated or is there an issue with the livekit transport currently available?

**Comment by aconchillo** [comment]
> # Description
> I saw in a previous issue that livekit support was added but i dont see it being mentioned in the documentation. Is the documentation just outdated or is there an issue with the livekit transport currently available?

Documentation is just outdated, the LiveKit transport should work (only audio though).

See https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/01b-livekit-audio.py
