### ISSUE TITLE
Feature request: Expo client SDK

### ISSUE THREAD

**Issue by jadams777** [pipecat-ai/pipecat#862]
LiveKit has an Expo client SDK. Would be great if PipeCat had one, too. 

- https://docs.livekit.io/home/quickstarts/expo/
- https://github.com/livekit/client-sdk-react-native-expo-plugin

**Comment by markbackman** [comment]
We already have Expo support.

- Pipecat client: https://github.com/pipecat-ai/rtvi-client-react-native-daily (This will be renamed to `pipecat-client-react-native-daily) this week.
- Expo plugin: https://github.com/daily-co/rn-daily-js-expo-config-plugin, which supports 52 as the latest.

We'll better document this in the Pipecat docs. Closing for now. We can reopen if you have any issues.
