### ISSUE TITLE
Broken links to documentation in README

### ISSUE THREAD

**Issue by evmar** [pipecat-ai/pipecat#864]
The "Getting started" section of the README
https://github.com/pipecat-ai/pipecat?tab=readme-ov-file#getting-started

Contain a bunch of links here
https://github.com/pipecat-ai/pipecat/blob/09a611d44ba09c8b875c95fc6cdfcc98d3b7bee3/README.md?plain=1#L60

None of these work, they just take you to the front page.

**Comment by Regaddi** [comment]
Links have been fixed via f90cbe8086af56bbca29d439491769aabe1e1c0e 🎸
