### ISSUE TITLE
Cartesia websocket infinite retires with no backoff

### ISSUE THREAD

**Issue by nikcaryo-super** [pipecat-ai/pipecat#871]
# Description
Is this reporting a bug or feature request?
Bug

If reporting a bug, please fill out the following:
pipecat-ai[silero,openai,deepgram,cartesia]==
### Environment
- pipecat-ai version: 0.0.50
- python version: 3.10
- OS: mac/linux

### Issue description
Provide a clear description of the issue.

When unable to connect to a Cartesia websocket, in our case because of hitting the concurrency limit, the websocket retries infinitely, causing cascading failures of other ongoing calls. 

relevant pr: https://github.com/pipecat-ai/pipecat/pull/796

### Repro steps
List the steps to reproduce the issue.
- start more calls with cartesia than your concurrency limits allowed

### Expected behavior
- after a certain number of websocket reconnect attempts, with exponential backoff of some sort, the pipeline exits

### Actual behavior
- websocket reconnects happen continuously without any behavior and never hit any max attempts

### Logs

```
Dec 16 04:23:41 PM
2024-12-16 16:23:41.690 | DEBUG    | pipecat.services.cartesia:_disconnect_websocket:214 - Disconnecting from Cartesia
Dec 16 04:23:41 PM
2024-12-16 16:23:41.691 | DEBUG    | pipecat.services.cartesia:_connect_websocket:201 - Connecting to Cartesia
Dec 16 04:23:43 PM
2024-12-16 16:23:43.361 | ERROR    | pipecat.services.cartesia:_receive_task_handler:285 - CartesiaDTMFService#5 exception: no close frame received or sent
Dec 16 04:23:43 PM
2024-12-16 16:23:43.361 | DEBUG    | pipecat.services.cartesia:_disconnect_websocket:214 - Disconnecting from Cartesia
Dec 16 04:23:43 PM
2024-12-16 16:23:43.361 | DEBUG    | pipecat.services.cartesia:_connect_websocket:201 - Connecting to Cartesia
Dec 16 04:23:43 PM
2024-12-16 16:23:43.453 | ERROR    | pipecat.services.cartesia:_receive_task_handler:285 - CartesiaDTMFService#2 exception: no close frame received or sent
Dec 16 04:23:43 PM
```

**Comment by ad12** [comment]
> From Timothy Luong at cartesia – websocket should open right before generation starts and then close, not be open for the duration of the conversation
> 
> > Current recommendation is to only open a websocket when there's expectation that your program/agent is about to speak
> 
> > The suggestion is that it's likely the case that some exception is occurring at some point in your conversation (maybe related to end of conversation) which would result in another websocket being opened, but maybe new websockets are opened for subsequent conversations or turns of conversations causing even 3 containers to have a monotonically increasing number of websockets.

Hey Nik! Just wanted to chime in here.

We recommend keeping a single WS open for as long as the conversation persists (across multiple turns). You would only need to close the WS once the full conversation is done. You don't need to close/open WS after each generation (i.e. after each turn)

**Comment by chongzluong** [comment]
Ah @nikcaryo-super apologies, my comment was more with regards to opening websockets for agents that aren't speaking at all (for example, we were seeing 130 websockets open with 0 concurrent generations). Within a single conversation you should only need one websocket.

**Comment by aconchillo** [comment]
Pipecat 0.0.51 fixes infinite reconnections with 3 attempts and exponential backoff.

**Comment by nikcaryo-super** [comment]
@chongzluong ahhh gotcha that makes sense - yeah we definitely wait to open the websocket until the conversation has actually started, so it must've just been the series of retries and hanging calls that made it look like there were websockets without actual conversations.
